name: create-release-notes
on:
  push:
    tags:
     - '*'
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '::set-output name=CURRENT_TAG::$(git --no-pager tag | sort -r | head -1)'
        id: set-current
      - run: echo '::set-output name=LAST_TAG::$(git --no-pager tag | sort -r | head -2 | tail -1)'
        id: set-last
      - run: echo '::set-output name=MESSAGES::$(git --no-pager log ${{ steps.set-last.outputs.LAST_TAG }}..HEAD --format=%s)'
        id: set-messages
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.set-current.outputs.CURRENT_TAG }}
          body: ${{ steps.set-messages.outputs.MESSAGES }}
          token: ${{ secrets.GITHUB_TOKEN }}